### ISSUE TITLE
return promise instead of callback (async/await support)

### ISSUE THREAD

**Issue by benatkin** [faaslang/faaslang#17]
How about support for returning a promise instead of using a callback? Then async/await could be supported (through TypeScript, through Babel, or when one of the major cloud function providers adds support for node 8).

**Comment by keithwhor** [comment]
Hey @benatkin - can you specify what you mean? We allow the use of async functions with FaaSlang, which supports `async` and `await`.

**Comment by benatkin** [comment]
I see. I must have missed the first time I read the README.
