### ISSUE TITLE
Question on adoption

### ISSUE THREAD

**Issue by alexellis** [faaslang/faaslang#22]
Hi Keith, I wanted to ask a question on adoption.

Who are the adopters of FaaS Lang? Do any of the significant serverless function providers implement FaaS Lang and do you see scope for the "FaaS Lang" beyond Node.js?

Thanks,

Alex

**Comment by keithwhor** [comment]
Hey Alex,

Got a hold of you on Twitter, but tl;dr is all https://stdlib.com developers, not yet but things in motion, and yes of course - but not a priority right now.

- Keith

**Comment by alexellis** [comment]
Thanks - good to know. And you don't have plans to extend beyond Node.js?
