### ISSUE TITLE
TypeScript vs JSDoc?

### ISSUE THREAD

**Issue by transitive-bullshit** [faaslang/faaslang#34]
First off, `faalang` looks really well done!

It's currently being used by `stdlib`, correct?

I was wondering what you think of supporting TypeScript for function signatures? And/or are there any related initiatives that you know of that might have TS support?

I'm just trying to get a better holistic understanding of the options available in this space overall. 💯 agreed that the lack of standardization around serverless function definitions is a problem.

Thanks!!

**Comment by keithwhor** [comment]
Hey! Seems like your questions were answered in our Slack -- TS not currently on roadmap, but we're not ruling it out in the future :).
