### ISSUE TITLE
3rd argument for callback function is not documented

### ISSUE THREAD

**Issue by adius** [faaslang/faaslang#5]
It's obviously possible to pass a headers object as 3rd argument to the callback function.
Why is this not documented?

(Also mentioned in https://github.com/stdlib/lib/issues/47)

**Comment by jacoblee93** [comment]
Thanks for bringing this up! We'll add it to the StdLib [docs page](https://docs.stdlib.com/main) shortly. FaaSlang is not necessarily meant to be used with HTTP, however, so we'll have to think about how we want to do documentation for this repo.

**Comment by keithwhor** [comment]
I've added a section to the README to cover this. :)
