### ISSUE TITLE
Add documentation for serving HTML

### ISSUE THREAD

**Issue by adius** [faaslang/faaslang#6]
I just spend way too much time to figure out how to server a HTML page.
If it wasn't for the vue template (https://docs.stdlib.com/main/#/templates/vue) I guess I would never have realized that I actually have to return a `new Buffer()` ^^

**Comment by jacoblee93** [comment]
Sorry about the confusion! We've just added a new section to the docs here: https://docs.stdlib.com/main/#/creating-services/the-callback-function

Thanks again for bringing this to our attention.

**Comment by adius** [comment]
Cool, thanks! I like your response time 😁
